// <auto-generated />
using Lotteri.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Lotteri.Migrations
{
    [DbContext(typeof(LotteriContext))]
    [Migration("20180314085113_update")]
    partial class update
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lotteri.Models.LottoItemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateFrom");

                    b.Property<DateTime>("DateTo");

                    b.Property<bool>("IsVisible");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("LottoItemModel");
                });

            modelBuilder.Entity("Lotteri.Models.Subscriber", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<int?>("LottoItemModelId");

                    b.Property<string>("Name");

                    b.Property<string>("Uid");

                    b.HasKey("Id");

                    b.HasIndex("LottoItemModelId");

                    b.ToTable("Subscriber");
                });

            modelBuilder.Entity("Lotteri.Models.Subscriber", b =>
                {
                    b.HasOne("Lotteri.Models.LottoItemModel")
                        .WithMany("Subscribers")
                        .HasForeignKey("LottoItemModelId");
                });
#pragma warning restore 612, 618
        }
    }
}
